window.menuItems = [
    { id: 1, name: "Paneer Tikka", desc: "Tandoori grilled paneer cubes.", img: "paneer_tikka.jpg", price: 180, category: "Starters", veg: true },
    { id: 2, name: "Veg Spring Rolls", desc: "Crispy rolls stuffed with veggies.", img: "veg_spring_rolls.jpg", price: 110, category: "Starters", veg: true },
    { id: 3, name: "Hara Bhara Kebab", desc: "Spinach, peas & potato cutlets.", img: "hara_bhara_kebab.jpg", price: 120, category: "Starters", veg: true },
    { id: 4, name: "Chilli Mushroom", desc: "Spicy Indo-Chinese mushrooms.", img: "chilli_mushroom.jpg", price: 130, category: "Starters", veg: true },
    { id: 5, name: "Corn Cheese Balls", desc: "Fried balls with corn & cheese.", img: "corn_cheese_balls.jpg", price: 125, category: "Starters", veg: true },
    { id: 6, name: "Crispy Baby Corn", desc: "Batter-fried baby corn.", img: "crispy_baby_corn.jpg", price: 115, category: "Starters", veg: true },
    { id: 7, name: "Tandoori Broccoli", desc: "Charred broccoli with spices.", img: "tandoori_broccoli.jpg", price: 140, category: "Starters", veg: true },

    { id: 8, name: "Dal Makhani", desc: "Slow-cooked creamy black lentils.", img: "dal_makhani.jpg", price: 180, category: "Main Course", veg: true },
    { id: 9, name: "Paneer Butter Masala", desc: "Paneer in tomato buttery gravy.", img: "paneer_butter_masala.jpg", price: 200, category: "Main Course", veg: true },
    { id: 10, name: "Aloo Gobi Masala", desc: "Potatoes & cauliflower in spices.", img: "aloo_gobi.jpg", price: 145, category: "Main Course", veg: true },
    { id: 11, name: "Veg Jalfrezi", desc: "Tangy mixed vegetables.", img: "veg_jalfrezi.jpg", price: 155, category: "Main Course", veg: true },
    { id: 12, name: "Kadai Paneer", desc: "Paneer in spicy onion-tomato curry.", img: "kadai_paneer.jpg", price: 190, category: "Main Course", veg: true },
    { id: 13, name: "Chana Masala", desc: "Rich chickpea curry.", img: "chana_masala.jpg", price: 140, category: "Main Course", veg: true },
    { id: 14, name: "Baingan Bharta", desc: "Roasted eggplant mash.", img: "baingan_bharta.jpg", price: 145, category: "Main Course", veg: true },
    { id: 15, name: "Palak Paneer", desc: "Spinach gravy with paneer.", img: "palak_paneer.jpg", price: 175, category: "Main Course", veg: true },

    { id: 16, name: "Butter Naan", desc: "Soft flatbread with butter.", img: "butter_naan.jpg", price: 45, category: "Breads & Rice", veg: true },
    { id: 17, name: "Jeera Rice", desc: "Cumin flavored rice.", img: "jeera_rice.jpg", price: 80, category: "Breads & Rice", veg: true },
    { id: 18, name: "Veg Pulao", desc: "Rice with vegetables.", img: "veg_pulao.jpg", price: 125, category: "Breads & Rice", veg: true },
    { id: 19, name: "Tandoori Roti", desc: "Whole wheat flatbread.", img: "tandoori_roti.jpg", price: 30, category: "Breads & Rice", veg: true },
    { id: 20, name: "Lachha Paratha", desc: "Flaky layered paratha.", img: "lachha_paratha.jpg", price: 40, category: "Breads & Rice", veg: true },
    { id: 21, name: "Steamed Rice", desc: "Plain steamed rice.", img: "steamed_rice.jpg", price: 70, category: "Breads & Rice", veg: true },
    { id: 22, name: "Peas Pulao", desc: "Rice with green peas.", img: "peas_pulao.jpg", price: 110, category: "Breads & Rice", veg: true },
    { id: 23, name: "Missi Roti", desc: "Gram flour flatbread.", img: "missi_roti.jpg", price: 35, category: "Breads & Rice", veg: true },

    { id: 24, name: "Masala Fries", desc: "Fries with Indian spice mix.", img: "masala_fries.jpg", price: 70, category: "Sides", veg: true },
    { id: 25, name: "Raita", desc: "Chilled yogurt with veggies.", img: "raita.jpg", price: 55, category: "Sides", veg: true },
    { id: 26, name: "Papad", desc: "Crispy lentil wafers.", img: "papad.jpg", price: 30, category: "Sides", veg: true },
    { id: 27, name: "Onion Salad", desc: "Fresh onion, lemon & chilli.", img: "onion_salad.jpg", price: 40, category: "Sides", veg: true },
    { id: 28, name: "Pickle", desc: "Indian mixed pickle.", img: "pickle.jpg", price: 20, category: "Sides", veg: true },
    { id: 29, name: "Green Salad", desc: "Fresh veggie salad.", img: "green_salad.jpg", price: 45, category: "Sides", veg: true },
    { id: 30, name: "Paneer Pakora", desc: "Paneer fritters.", img: "paneer_pakora.jpg", price: 90, category: "Sides", veg: true },

    { id: 31, name: "Mango Lassi", desc: "Mango yogurt drink.", img: "mango_lassi.jpg", price: 70, category: "Drinks", veg: true },
    { id: 32, name: "Sweet Lime Soda", desc: "Homemade lemonade.", img: "lime_soda.jpg", price: 50, category: "Drinks", veg: true },
    { id: 33, name: "Rose Milk", desc: "Chilled sweetened milk.", img: "rose_milk.jpg", price: 65, category: "Drinks", veg: true },
    { id: 34, name: "Salted Lassi", desc: "Salty yogurt drink.", img: "salted_lassi.jpg", price: 60, category: "Drinks", veg: true },
    { id: 35, name: "Masala Chaas", desc: "Spiced buttermilk.", img: "masala_chaas.jpg", price: 45, category: "Drinks", veg: true },
    { id: 36, name: "Filter Coffee", desc: "South Indian filter coffee.", img: "filter_coffee.jpg", price: 50, category: "Drinks", veg: true },
    { id: 37, name: "Soft Drink", desc: "Choice of carbonated beverage.", img: "soft_drink.jpg", price: 40, category: "Drinks", veg: true },

    { id: 38, name: "Gulab Jamun", desc: "Syrupy sweet dumplings.", img: "gulab_jamun.jpg", price: 60, category: "Desserts", veg: true },
    { id: 39, name: "Kulfi", desc: "Traditional Indian ice cream.", img: "kulfi.jpg", price: 80, category: "Desserts", veg: true },
    { id: 40, name: "Moong Dal Halwa", desc: "Rich ghee-based halwa.", img: "moong_dal_halwa.jpg", price: 90, category: "Desserts", veg: true },
    { id: 41, name: "Rasgulla", desc: "Spongy syrupy balls.", img: "rasgulla.jpg", price: 75, category: "Desserts", veg: true },
    { id: 42, name: "Kheer", desc: "Rice pudding with nuts.", img: "kheer.jpg", price: 80, category: "Desserts", veg: true },
    { id: 43, name: "Jalebi", desc: "Crisp syrupy coils.", img: "jalebi.jpg", price: 60, category: "Desserts", veg: true },
    { id: 44, name: "Fruit Salad", desc: "Fresh fruits & cream.", img: "fruit_salad.jpg", price: 90, category: "Desserts", veg: true },

    { id: 45, name: "Punjabi Combo", desc: "Dal, Paneer, Naan, Raita.", img: "punjabi_combo.jpg", price: 340, category: "Combos", veg: true },
    { id: 46, name: "South Indian Combo", desc: "Rice, Sambar, Poriyal, Curd.", img: "south_combo.jpg", price: 300, category: "Combos", veg: true },
    { id: 47, name: "North Indian Thali", desc: "Assorted curries, breads, dessert.", img: "north_thali.jpg", price: 360, category: "Combos", veg: true },
    { id: 48, name: "Paratha Combo", desc: "Assorted parathas, sabji, curd.", img: "paratha_combo.jpg", price: 270, category: "Combos", veg: true },
    { id: 49, name: "Mini Meal", desc: "Rice, dal, veg curry, roti.", img: "mini_meal.jpg", price: 210, category: "Combos", veg: true },
    { id: 50, name: "Street Food Combo", desc: "Chaat, samosa, lassi.", img: "street_combo.jpg", price: 220, category: "Combos", veg: true },
    { id: 51, name: "Paneer Lovers", desc: "Paneer starter, main, bread.", img: "paneer_lovers.jpg", price: 320, category: "Combos", veg: true },

    { id: 101, name: "Chicken Tikka", desc: "Char-grilled spicy chicken cubes.", img: "chicken_tikka.jpg", price: 200, category: "Starters", veg: false },
    { id: 102, name: "Fish Fingers", desc: "Crispy battered fish sticks.", img: "fish_fingers.jpg", price: 190, category: "Starters", veg: false },
    { id: 103, name: "Egg Pakora", desc: "Eggs battered and fried.", img: "egg_pakora.jpg", price: 120, category: "Starters", veg: false },
    { id: 104, name: "Tandoori Prawns", desc: "Grilled prawns with spices.", img: "tandoori_prawns.jpg", price: 240, category: "Starters", veg: false },
    { id: 105, name: "Chicken Seekh Kebab", desc: "Minced chicken skewered.", img: "chicken_seekh.jpg", price: 180, category: "Starters", veg: false },
    { id: 106, name: "Mutton Shami Kebab", desc: "Minced mutton patties.", img: "mutton_shami.jpg", price: 195, category: "Starters", veg: false },
    { id: 107, name: "Chicken Lollipop", desc: "Fried chicken wings.", img: "chicken_lollipop.jpg", price: 160, category: "Starters", veg: false },

    { id: 108, name: "Butter Chicken", desc: "Creamy tomato chicken curry.", img: "butter_chicken.jpg", price: 240, category: "Main Course", veg: false },
    { id: 109, name: "Mutton Rogan Josh", desc: "Tender mutton in rich gravy.", img: "rogan_josh.jpg", price: 250, category: "Main Course", veg: false },
    { id: 110, name: "Egg Curry", desc: "Eggs in spicy onion-tomato gravy.", img: "egg_curry.jpg", price: 150, category: "Main Course", veg: false },
    { id: 111, name: "Fish Curry", desc: "Coastal fish in spicy gravy.", img: "fish_curry.jpg", price: 210, category: "Main Course", veg: false },
    { id: 112, name: "Chicken Chettinad", desc: "Spicy South Indian chicken curry.", img: "chicken_chettinad.jpg", price: 220, category: "Main Course", veg: false },
    { id: 113, name: "Prawn Masala", desc: "Prawns in spicy masala.", img: "prawn_masala.jpg", price: 245, category: "Main Course", veg: false },
    { id: 114, name: "Bhuna Gosht", desc: "Stir-fried mutton curry.", img: "bhuna_gosht.jpg", price: 240, category: "Main Course", veg: false },
    { id: 115, name: "Chicken Do Pyaza", desc: "Chicken with onions & spices.", img: "chicken_do_pyaza.jpg", price: 210, category: "Main Course", veg: false },

    { id: 116, name: "Garlic Naan", desc: "Naan topped with garlic.", img: "garlic_naan.jpg", price: 55, category: "Breads & Rice", veg: false },
    { id: 117, name: "Chicken Biryani", desc: "Spiced rice with chicken.", img: "chicken_biryani.jpg", price: 220, category: "Breads & Rice", veg: false },
    { id: 118, name: "Egg Fried Rice", desc: "Egg and veggies with rice.", img: "egg_fried_rice.jpg", price: 110, category: "Breads & Rice", veg: false },
    { id: 119, name: "Keema Naan", desc: "Bread stuffed with minced meat.", img: "keema_naan.jpg", price: 70, category: "Breads & Rice", veg: false },
    { id: 120, name: "Mutton Biryani", desc: "Spiced rice with mutton.", img: "mutton_biryani.jpg", price: 250, category: "Breads & Rice", veg: false },
    { id: 121, name: "Egg Paratha", desc: "Paratha stuffed with egg.", img: "egg_paratha.jpg", price: 60, category: "Breads & Rice", veg: false },
    { id: 122, name: "Fish Pulao", desc: "Rice cooked with fish.", img: "fish_pulao.jpg", price: 160, category: "Breads & Rice", veg: false },

    { id: 123, name: "Chicken Popcorn", desc: "Crispy chicken bites.", img: "chicken_popcorn.jpg", price: 95, category: "Sides", veg: false },
    { id: 124, name: "Egg Salad", desc: "Boiled eggs with salad.", img: "egg_salad.jpg", price: 70, category: "Sides", veg: false },
    { id: 125, name: "Fish Cutlet", desc: "Minced fish patties.", img: "fish_cutlet.jpg", price: 90, category: "Sides", veg: false },
    { id: 126, name: "Chicken Pakora", desc: "Fried chicken fritters.", img: "chicken_pakora.jpg", price: 100, category: "Sides", veg: false },
    { id: 127, name: "Egg Bhurji", desc: "Spicy scrambled eggs.", img: "egg_bhurji.jpg", price: 70, category: "Sides", veg: false },
    { id: 128, name: "Mutton Kebab", desc: "Char-grilled mutton skewers.", img: "mutton_kebab.jpg", price: 120, category: "Sides", veg: false },
    { id: 129, name: "Chicken Sausage", desc: "Grilled chicken sausage.", img: "chicken_sausage.jpg", price: 80, category: "Sides", veg: false },

    { id: 130, name: "Fresh Lime Soda", desc: "Refreshing lime drink.", img: "fresh_lime_soda.jpg", price: 60, category: "Drinks", veg: false },
    { id: 131, name: "Masala Chai", desc: "Spiced Indian tea.", img: "masala_chai.jpg", price: 40, category: "Drinks", veg: false },
    { id: 132, name: "Cold Coffee", desc: "Chilled coffee.", img: "cold_coffee.jpg", price: 65, category: "Drinks", veg: false },
    { id: 133, name: "Lassi", desc: "Sweet or salted yogurt drink.", img: "lassi.jpg", price: 60, category: "Drinks", veg: false },
    { id: 134, name: "Buttermilk", desc: "Spiced yogurt drink.", img: "buttermilk.jpg", price: 50, category: "Drinks", veg: false },
    { id: 135, name: "Soft Drink", desc: "Choice of soft drink.", img: "soft_drink1.jpg", price: 40, category: "Drinks", veg: false },
    { id: 136, name: "Lemon Iced Tea", desc: "Chilled lemony tea.", img: "lemon_iced_tea.jpg", price: 55, category: "Drinks", veg: false },

    { id: 137, name: "Brownie with Ice Cream", desc: "Warm brownie & vanilla scoop.", img: "brownie_icecream.jpg", price: 110, category: "Desserts", veg: false },
    { id: 138, name: "Caramel Custard", desc: "Soft caramel pudding.", img: "caramel_custard.jpg", price: 90, category: "Desserts", veg: false },
    { id: 139, name: "Phirni", desc: "Rice pudding with saffron.", img: "phirni.jpg", price: 80, category: "Desserts", veg: false },
    { id: 140, name: "Eggless Mousse", desc: "Chocolate mousse dessert.", img: "eggless_mousse.jpg", price: 95, category: "Desserts", veg: false },
    { id: 141, name: "Ice Cream Sundae", desc: "Ice cream, nuts & syrup.", img: "ice_cream_sundae.jpg", price: 85, category: "Desserts", veg: false },
    { id: 142, name: "Fruit Custard", desc: "Fruits in creamy custard.", img: "fruit_custard.jpg", price: 80, category: "Desserts", veg: false },
    { id: 143, name: "Malai Kulfi", desc: "Rich creamy kulfi.", img: "malai_kulfi.jpg", price: 90, category: "Desserts", veg: false },

    { id: 144, name: "Chicken Combo", desc: "Biryani, Butter Chicken, Naan.", img: "nonveg_combo.jpg", price: 420, category: "Combos", veg: false },
    { id: 145, name: "Mutton Feast", desc: "Rogan Josh, rice, paratha.", img: "mutton_feast.jpg", price: 470, category: "Combos", veg: false },
    { id: 146, name: "Seafood Platter", desc: "Fish, prawns, rice.", img: "seafood_platter.jpg", price: 480, category: "Combos", veg: false },
    { id: 147, name: "Egg Meal", desc: "Egg curry, rice, salad.", img: "egg_meal.jpg", price: 280, category: "Combos", veg: false },
    { id: 148, name: "Chicken Grill Combo", desc: "Chicken starter, main, naan.", img: "chicken_grill_combo.jpg", price: 390, category: "Combos", veg: false },
    { id: 149, name: "Kebab Platter", desc: "Assorted kebabs, bread.", img: "kebab_platter.jpg", price: 350, category: "Combos", veg: false },
    { id: 150, name: "Non-Veg Thali", desc: "Chicken, mutton, rice, dessert.", img: "nonveg_thali.jpg", price: 520, category: "Combos", veg: false }
];

window.categories = [
    { label: "Starters", icon: "🥗" },
    { label: "Main Course", icon: "🍛" },
    { label: "Breads & Rice", icon: "🍚" },
    { label: "Sides", icon: "🍟" },
    { label: "Drinks", icon: "🍷" },
    { label: "Desserts", icon: "🍰" },
    { label: "Combos", icon: "🍽️" }
];